version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: yarn install
      - run: yarn test
  hithere:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run: echo "helloo!"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere